[toolchain]
channel = '1.75.0'
# components = ["rustfmt", "clippy"]
# TODO let new machine auto use this like exec: `rustup target add wasm32-unknown-unknown` in cmd.
targets = ["wasm32-unknown-unknown"]
